name: 'Infrastructure Configuring using Terraform on AWS'

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Terraform Action'
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'plan'

permissions:
  contents: read

jobs:
  infrastructure-setup-using-terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-24.04
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: Terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-ter        uses: hashicorp/setup-ter        useser        uses: hashicorp/setup-ter        uses: hashicorp: terra        uses: hashiname: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ git        if:nputs.        i 'plan' }}
        run: terra        run: terra   e
        run: terra    rm         run          run: te.event.inputs.action == 'apply' }}
        run: t        run: t        run: t        - name: Terraform         run: t        rugi        nt.inputs.action == 'destroy' }}
        run:         run:stroy -auto-approve
